<?php
session_start();
require_once 'config.php';
require_once 'database.php';
require_once 'lib/fpdf.php'; // For is_fpdf_installed() check and potential placeholder message

// Authentication Check
if (!isset($_SESSION['user_id'])) {
    header("Location: index.php");
    exit;
}

$current_user_id = $_SESSION['user_id'];
$current_user_name = $_SESSION['user_name']; 

$page_message = '';
$task_stats = [];

// Define possible statuses (from schema.sql ENUM)
$defined_statuses = ['pending', 'in_progress', 'completed', 'cancelled'];

$db = get_db_connection();
if ($db) {
    $task_stats = get_task_counts_by_status($db, $current_user_id);
    // Potentially fetch distinct statuses if needed for the form, though $defined_statuses is safer.
    // $distinct_statuses_query = $db->query("SELECT DISTINCT status FROM tasks");
    // while($status_row = $distinct_statuses_query->fetch_assoc()){ $available_statuses[] = $status_row['status']; }
    close_db_connection($db);
} else {
    $page_message = '<p class="text-red-500 text-center mb-4">Critical: Database connection failed. Cannot load page data.</p>';
}

// PDF Generation Logic
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action']) && $_POST['action'] === 'generate_pdf') {
    if (!is_fpdf_installed()) {
        $page_message .= "<div class='message-box errors'>PDF Generation is currently unavailable as FPDF library is not installed. Please see <code>lib/fpdf.php</code> for instructions.</div>";
    } else {
        $selected_statuses = $_POST['statuses'] ?? [];
        $start_date = !empty($_POST['start_date']) ? trim($_POST['start_date']) : null;
        $end_date = !empty($_POST['end_date']) ? trim($_POST['end_date']) : null;

        $db_report = get_db_connection();
        if (!$db_report) {
            $page_message .= "<div class='message-box errors'>Database connection failed for report generation.</div>";
        } else {
            $report_tasks = get_tasks_for_report($db_report, $current_user_id, $selected_statuses, $start_date, $end_date);

            if (empty($report_tasks)) {
                $page_message .= "<div class='message-box info'>No tasks found matching your selected criteria for the PDF report.</div>";
            } else {
                // Pre-fetch all user details for the report
                $report_user_ids = [];
                foreach ($report_tasks as $task) {
                    if (!empty($task['user_id'])) $report_user_ids[] = $task['user_id'];
                    if (!empty($task['assigned_to_user_id'])) $report_user_ids[] = $task['assigned_to_user_id'];
                }
                $report_user_ids = array_unique(array_filter($report_user_ids));
                $report_user_details_cache = [];
                foreach ($report_user_ids as $uid) {
                    $user_info = get_user_by_id($db_report, $uid);
                    if ($user_info) $report_user_details_cache[$uid] = $user_info;
                }

                // FPDF Generation
                $pdf = new FPDF('L', 'mm', 'A4'); // Landscape, mm, A4
                $pdf->SetAuthor("Task Manager Application");
                $pdf->SetTitle("Task Report");
                $pdf->AddPage();
                
                // Report Title
                $pdf->SetFont('Arial', 'B', 16);
                $pdf->Cell(0, 10, 'Task Report', 0, 1, 'C');
                $pdf->Ln(5);

                // Filter Info
                $pdf->SetFont('Arial', '', 10);
                $filter_text = "Generated by: " . htmlspecialchars($current_user_name) . " on " . date("Y-m-d H:i:s") . "\n";
                $filter_text .= "Filters Applied:\n";
                $filter_text .= "  Statuses: " . (!empty($selected_statuses) ? implode(', ', array_map('ucfirst', $selected_statuses)) : 'All') . "\n";
                $filter_text .= "  Due Date Range: " . (!empty($start_date) ? $start_date : 'Any') . " to " . (!empty($end_date) ? $end_date : 'Any') . "\n";
                $pdf->MultiCell(0, 6, $filter_text, 0, 'L');
                $pdf->Ln(5);

                // Table Header
                $pdf->SetFont('Arial', 'B', 9);
                $pdf->SetFillColor(230, 230, 230);
                $header_widths = [55, 25, 20, 20, 35, 35, 75]; // Adjusted for landscape & new fields
                $pdf->Cell($header_widths[0], 7, 'Title', 1, 0, 'C', true);
                $pdf->Cell($header_widths[1], 7, 'Status', 1, 0, 'C', true);
                $pdf->Cell($header_widths[2], 7, 'Priority', 1, 0, 'C', true);
                $pdf->Cell($header_widths[3], 7, 'Due Date', 1, 0, 'C', true);
                $pdf->Cell($header_widths[4], 7, 'Creator', 1, 0, 'C', true);
                $pdf->Cell($header_widths[5], 7, 'Assignee', 1, 0, 'C', true);
                $pdf->Cell($header_widths[6], 7, 'Description', 1, 1, 'C', true);


                // Table Rows
                $pdf->SetFont('Arial', '', 8);
                $pdf->SetFillColor(255, 255, 255);
                $fill = false;
                foreach ($report_tasks as $task) {
                    $creator_name = isset($report_user_details_cache[$task['user_id']]) ? $report_user_details_cache[$task['user_id']]['name'] : 'N/A';
                    $assignee_name = !empty($task['assigned_to_user_id']) && isset($report_user_details_cache[$task['assigned_to_user_id']]) ? $report_user_details_cache[$task['assigned_to_user_id']]['name'] : 'Unassigned';
                    
                    // Handle potential multi-line for title and description more gracefully.
                    // Store current Y position
                    $y_pos = $pdf->GetY();
                    
                    // Title (MultiCell for wrapping)
                    $pdf->MultiCell($header_widths[0], 6, iconv('UTF-8', 'windows-1252', $task['title'] ?: 'N/A'), 1, 'L', $fill);
                    $x_pos_after_title = $pdf->GetX() + $header_widths[0]; // Calculate X for next cell
                    $y_pos_after_title = $pdf->GetY(); // Y after MultiCell
                    $pdf->SetXY($x_pos_after_title, $y_pos); // Reset Y to start of row, X to next cell

                    $pdf->Cell($header_widths[1], 6, ucfirst($task['status'] ?: 'N/A'), 1, 0, 'L', $fill);
                    $pdf->Cell($header_widths[2], 6, ucfirst($task['priority'] ?: 'N/A'), 1, 0, 'L', $fill);
                    $pdf->Cell($header_widths[3], 6, $task['due_date'] ? date("Y-m-d", strtotime($task['due_date'])) : 'N/A', 1, 0, 'L', $fill);
                    $pdf->Cell($header_widths[4], 6, iconv('UTF-8', 'windows-1252', $creator_name), 1, 0, 'L', $fill);
                    $pdf->Cell($header_widths[5], 6, iconv('UTF-8', 'windows-1252', $assignee_name), 1, 0, 'L', $fill);

                    // Description (MultiCell for wrapping)
                    $x_pos_after_assignee = $pdf->GetX() + $header_widths[5];
                    $pdf->SetXY($x_pos_after_assignee - $header_widths[6], $y_pos); // Reset Y, X to start of description cell
                    $pdf->MultiCell($header_widths[6], 6, iconv('UTF-8', 'windows-1252', $task['description'] ?: 'N/A'), 1, 'L', $fill);
                    $y_pos_after_desc = $pdf->GetY();
                    
                    // Determine max Y to ensure next row starts correctly if MultiCells changed height
                    $final_y = max($y_pos_after_title, $y_pos_after_desc);
                    $pdf->SetY($final_y); // This might not be perfect for complex multi-line scenarios across all cells.
                                        // A common strategy is to calculate max height needed for the row first.
                                        // For simplicity, this attempts to align based on title/description.

                    $fill = !$fill;
                }
                
                close_db_connection($db_report);
                $pdf->Output('D', 'Task_Report_' . date("YmdHis") . '.pdf');
                exit;
            }
            if ($db_report) close_db_connection($db_report);
        }
    }
}


?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task Reports - Task Manager</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
    <script>
      window.OneSignal = window.OneSignal || [];
      OneSignal.push(function() {
        OneSignal.init({
          appId: "YOUR_ONESIGNAL_APP_ID", // From config.php or direct
          notifyButton: { enable: true },
          allowLocalhostAsSecureOrigin: true,
        });
        <?php if (isset($_SESSION['user_id'])): ?>
        OneSignal.setExternalUserId("<?php echo $_SESSION['user_id']; ?>");
        <?php endif; ?>
      });
    </script>
    <style>
        .stat-card { background-color: #fff; padding: 1.5rem; border-radius: 0.5rem; box-shadow: 0 4px 6px rgba(0,0,0,0.1); text-align: center; }
        .stat-card h3 { font-size: 1.125rem; color: #4a5568; margin-bottom: 0.5rem; }
        .stat-card p { font-size: 2rem; font-weight: bold; color: #2d3748; }
        .message-box { margin-bottom: 1rem; padding: 1rem; border-radius: 0.25rem; }
        .message-box.errors { background-color: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }
        .message-box.info { background-color: #d1ecf1; color: #0c5460; border: 1px solid #bee5eb; }
    </style>
</head>
<body class="bg-gray-100 min-h-screen">
    <header class="bg-white shadow-sm">
        <div class="container mx-auto px-6 py-4 flex justify-between items-center">
            <div>
                <a href="index.php" class="text-xl font-bold text-gray-700 hover:text-blue-600">Task Manager Home</a>
                <a href="my-task.php" class="ml-4 text-md text-blue-600 hover:text-blue-800">My Tasks</a>
            </div>
            <div class="flex items-center">
                <span class="text-gray-600 mr-4">Welcome, <?php echo htmlspecialchars($current_user_name); ?>!</span>
                <a href="index.php?action=logout" class="bg-red-500 text-white py-2 px-4 rounded-md hover:bg-red-600 transition-colors">Logout</a>
            </div>
        </div>
    </header>

    <main class="container mx-auto mt-8 p-6">
        <h1 class="text-3xl font-bold text-gray-800 mb-8">Task Reports</h1>

        <?php if (!empty($page_message)) echo $page_message; ?>

        <!-- Task Statistics -->
        <section class="mb-10">
            <h2 class="text-2xl font-semibold text-gray-700 mb-6">My Task Statistics</h2>
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-6">
                <div class="stat-card border-l-4 border-yellow-400">
                    <h3>Pending</h3>
                    <p><?php echo $task_stats['pending'] ?? 0; ?></p>
                </div>
                <div class="stat-card border-l-4 border-blue-400">
                    <h3>In Progress</h3>
                    <p><?php echo $task_stats['in_progress'] ?? 0; ?></p>
                </div>
                <div class="stat-card border-l-4 border-green-400">
                    <h3>Completed</h3>
                    <p><?php echo $task_stats['completed'] ?? 0; ?></p>
                </div>
                <div class="stat-card border-l-4 border-red-400">
                    <h3>Cancelled</h3>
                    <p><?php echo $task_stats['cancelled'] ?? 0; ?></p>
                </div>
                <div class="stat-card border-l-4 border-gray-500">
                    <h3>Total Tasks</h3>
                    <p><?php echo $task_stats['total'] ?? 0; ?></p>
                </div>
            </div>
        </section>

        <!-- PDF Report Generation Form -->
        <section class="bg-white p-6 rounded-lg shadow-md">
            <h2 class="text-2xl font-semibold text-gray-700 mb-6 border-b pb-3">Generate PDF Report</h2>
            <form action="report.php" method="POST" class="space-y-6">
                <input type="hidden" name="action" value="generate_pdf">

                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Task Statuses (select one or more)</label>
                    <select name="statuses[]" id="statuses" multiple class="w-full p-2.5 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 h-32">
                        <?php foreach ($defined_statuses as $status): ?>
                            <option value="<?php echo htmlspecialchars($status); ?>">
                                <?php echo ucfirst(str_replace('_', ' ', htmlspecialchars($status))); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                    <p class="text-xs text-gray-500 mt-1">Hold Ctrl (Cmd on Mac) to select multiple statuses.</p>
                </div>

                <div class="grid md:grid-cols-2 gap-6">
                    <div>
                        <label for="start_date" class="block text-sm font-medium text-gray-700 mb-1">Start Date (Due Date)</label>
                        <input type="date" name="start_date" id="start_date" class="w-full p-2.5 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500">
                    </div>
                    <div>
                        <label for="end_date" class="block text-sm font-medium text-gray-700 mb-1">End Date (Due Date)</label>
                        <input type="date" name="end_date" id="end_date" class="w-full p-2.5 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500">
                    </div>
                </div>
                
                <div>
                    <button type="submit" class="w-full bg-green-600 hover:bg-green-700 text-white font-bold py-3 px-4 rounded-md focus:outline-none focus:shadow-outline transition-colors duration-150 <?php if (!is_fpdf_installed()) echo 'opacity-50 cursor-not-allowed'; ?>" <?php if (!is_fpdf_installed()) echo 'disabled title="FPDF Library not installed"'; ?>>
                        Generate PDF Report <?php if (!is_fpdf_installed()) echo '(Disabled)'; ?>
                    </button>
                </div>
            </form>
             <?php if (!is_fpdf_installed()): ?>
                <p class="text-center text-sm text-red-600 mt-4">PDF generation is disabled because the FPDF library is not installed. Please see <code>lib/fpdf.php</code> for instructions.</p>
            <?php endif; ?>
        </section>
    </main>
</body>
</html>
